-- Script gerado para popular questoes da materia Ciencias Sociales y Medicina (slug = ciencias-sociales-y-medicina)
-- Faculdade: UNLP (Medicina UBA-UNLP, agrupamento_id = 3 — 1º Año)
-- Rodar inteiro de uma vez no phpMyAdmin (aba SQL) no banco de producao.
-- O arquivo storage/app/data/questoes_ciencias_sociales_y_medicina.json deve ser copiado antes.

INSERT IGNORE INTO materias (nome, slug, agrupamento_id, ordem)
VALUES ('Ciencias Sociales y Medicina', 'ciencias-sociales-y-medicina', 3, 10);

SET @materia_id = (SELECT id FROM materias WHERE slug = 'ciencias-sociales-y-medicina' LIMIT 1);

INSERT INTO questoes (materia_id, catedra_id, overlay_key, parcial, tema, is_demo, created_at, updated_at)
SELECT @materia_id, NULL, v.overlay_key, NULL, v.tema, (v.overlay_key < 12), NOW(), NOW()
FROM (
  SELECT 0 AS overlay_key, 'Módulo I: La Ciencia y el Método Científico' AS tema
  UNION ALL SELECT 1, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 2, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 3, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 4, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 5, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 6, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 7, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 8, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 9, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 10, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 11, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 12, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 13, 'Módulo I: La Ciencia y el Método Científico'
  UNION ALL SELECT 14, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 15, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 16, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 17, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 18, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 19, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 20, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 21, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 22, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 23, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 24, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 25, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 26, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 27, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 28, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 29, 'Módulo II: Bases Bioéticas y Derechos del Paciente'
  UNION ALL SELECT 30, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 31, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 32, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 33, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 34, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 35, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 36, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 37, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 38, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 39, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 40, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 41, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 42, 'Módulo III: Empatía y Psicología de la Salud'
  UNION ALL SELECT 43, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 44, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 45, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 46, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 47, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 48, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 49, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 50, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 51, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 52, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 53, 'Módulo IV: Comunicación en Salud'
  UNION ALL SELECT 54, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 55, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 56, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 57, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 58, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 59, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 60, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 61, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 62, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 63, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 64, 'Módulo V: Antropología Médica'
  UNION ALL SELECT 65, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 66, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 67, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 68, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 69, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 70, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 71, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 72, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 73, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 74, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 75, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 76, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
  UNION ALL SELECT 77, 'Módulo VI: Niveles de Atención y Promoción de la Salud'
) AS v;
